//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace katarfelek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class panelUsers
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Auth_Num { get; set; }
        public int ActiveSettingID { get; set; }
    }
}
